#!/usr/bin/env python3
"""Merge icon names into the manifest in icons.html.

    ./tools/icons-label.py names.json
    echo '{"finance": {"04": "invoice-paid"}}' | ./tools/icons-label.py -
    ./tools/icons-label.py --report

Input is {pack-slug: {icon-number: name}}. Merging, not replacing: a pack already
carrying names keeps the ones this patch doesn't mention, so naming can be done a
few packs at a time without holding the whole set in one file.

Names are the point of the icon library. `Finance-04` is unsearchable, and there
are 1,490 of them, so the difference between this library being useful and being
a wall of numbered squares is entirely in this file's output.

WHY A SCRIPT AND NOT HAND-EDITING
---------------------------------
The manifest is one JSON object per pack on one line, generated by icons-sync.py.
Hand-editing 80 of those lines is how you end up with a trailing comma at 2am and
a grid that renders nothing. This validates instead:

  - the pack exists
  - the icon number exists in that pack (no naming Finance-31 in a 30-icon pack)
  - the name is lowercase-hyphenated, so names sort and read consistently
  - nothing else in the manifest moves

It refuses the whole patch on any error rather than applying half of it.
Duplicate names across packs are allowed and reported, not blocked: a handshake
in Collaboration and a handshake in Client are both legitimately handshakes, and
the tile's tooltip carries the pack to tell them apart.
"""

import json
import re
import sys

ROOT = __file__.rsplit('/tools/', 1)[0]
PAGE = ROOT + '/icons.html'
BEGIN = '  <script type="application/json" id="icon-manifest">'
END = '  </script>'
NAME_RE = re.compile(r'^[a-z0-9]+(-[a-z0-9]+)*$')


def load():
    text = open(PAGE, encoding='utf-8').read()
    i = text.find(BEGIN)
    j = text.find(END, i + len(BEGIN)) if i >= 0 else -1
    if i < 0 or j < 0:
        sys.exit('error: could not find the manifest block in icons.html')
    return text, i + len(BEGIN), j, json.loads(text[i + len(BEGIN):j])


def render(data):
    lines = ['  {',
             '    "version": %s,' % json.dumps(data['version']),
             '    "generated": %s,' % json.dumps(data['generated']),
             '    "total": %d,' % data['total'],
             '    "packs": [']
    for n, p in enumerate(data['packs']):
        lines.append('      ' + json.dumps(p, ensure_ascii=False) +
                     ('' if n == len(data['packs']) - 1 else ','))
    lines += ['    ]', '  }']
    return '\n'.join(lines)


def report(data):
    named = total = 0
    seen = {}
    incomplete = []
    for p in data['packs']:
        labels = p.get('labels') or {}
        named += len(labels)
        total += p['count']
        if labels and len(labels) < p['count']:
            incomplete.append('%s (%d/%d)' % (p['slug'], len(labels), p['count']))
        for num, nm in labels.items():
            seen.setdefault(nm, []).append('%s-%s' % (p['slug'], num))
    print('named %d of %d icons (%.0f%%) across %d packs'
          % (named, total, 100.0 * named / total, sum(1 for p in data['packs'] if p.get('labels'))))
    done = [p['slug'] for p in data['packs'] if len(p.get('labels') or {}) == p['count']]
    print('complete packs : %d' % len(done))
    if incomplete:
        print('partial packs  : ' + ', '.join(incomplete))
    dupes = {k: v for k, v in seen.items() if len(v) > 1}
    if dupes:
        print('\nnames used more than once (allowed — the tooltip carries the pack):')
        for k in sorted(dupes)[:20]:
            print('  %-22s %s' % (k, ', '.join(dupes[k])))
        if len(dupes) > 20:
            print('  … and %d more' % (len(dupes) - 20))


def main():
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    text, start, end, data = load()

    if sys.argv[1] == '--report':
        return report(data)

    raw = sys.stdin.read() if sys.argv[1] == '-' else open(sys.argv[1], encoding='utf-8').read()
    try:
        patch = json.loads(raw)
    except ValueError as e:
        sys.exit('error: patch is not valid JSON — %s' % e)

    by_slug = {p['slug']: p for p in data['packs']}
    errors, applied, changed = [], 0, 0

    for slug, names in patch.items():
        pack = by_slug.get(slug)
        if not pack:
            errors.append('unknown pack "%s"' % slug)
            continue
        for num, name in names.items():
            if not re.fullmatch(r'\d{2}', str(num)):
                errors.append('%s: "%s" is not a two-digit icon number' % (slug, num))
            elif not 1 <= int(num) <= pack['count']:
                errors.append('%s: icon %s is outside this pack (1–%d)' % (slug, num, pack['count']))
            if not NAME_RE.match(name):
                errors.append('%s-%s: "%s" must be lowercase-hyphenated' % (slug, num, name))

    if errors:
        sys.exit('error: patch rejected, nothing written:\n  - ' + '\n  - '.join(errors))

    for slug, names in patch.items():
        pack = by_slug[slug]
        labels = dict(pack.get('labels') or {})
        for num, name in names.items():
            if labels.get(num) != name:
                changed += 1
            labels[num] = name
            applied += 1
        pack['labels'] = {k: labels[k] for k in sorted(labels)}

    open(PAGE, 'w', encoding='utf-8').write(text[:start] + '\n' + render(data) + '\n' + text[end:])
    print('applied %d names across %d pack(s), %d newly set or changed'
          % (applied, len(patch), changed))
    report(data)


if __name__ == '__main__':
    main()
